service: vitemadose-notifier

provider:
  name: google
  stage: dev
  runtime: python37
  region: us-central1
  project: hack-space-dev

frameworkVersion: "2"
plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  ifttt-trigger:
    handler: http
    events:
      - http: path
